# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-25 14:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_type', models.CharField(choices=[('LP', 'Album'), ('EP', 'EP'), ('SN', 'Single'), ('CM', 'Compilation'), ('LV', 'Live')], default='LP', max_length=2)),
                ('release_date', models.DateField(default=datetime.date.today, help_text='When the release is available to the public.')),
                ('pub_datetime', models.DateTimeField(default=django.utils.timezone.now, help_text='When the release will be made visible on-site.')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(unique=True)),
                ('tagline', models.CharField(blank=True, default='', max_length=200)),
                ('info', models.TextField(blank=True, default='')),
                ('cover', models.ImageField(default='missing.png', upload_to='covers')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('length', models.DurationField()),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='releases.Release')),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='releases.Release'),
        ),
    ]
