# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-11 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='cover',
            field=models.ImageField(upload_to='covers'),
        ),
    ]
