language: python
python:
        - "3.5"
install: pip install -r requirements/ci.txt
services:
        - postgresql
before_script:
        - psql -c 'create database travis_ci_test;' -U postgres
env:
        global:
                - SECRET_KEY="+&iy5xo9dad)e@1nmoxxn%ntdmo)krer#e5no50@74q62kwcrv"
                - DJANGO_SETTINGS_MODULE=syah_site.settings.ci
script:
        - coverage run --omit='manage.py' --source='.' manage.py test
        - coveralls
