language: python
python:
        - "3.5"
install: pip install -r requirements/ci.txt
services:
        - postgresql
before_script:
        - psql -c 'create database travis_ci_test;' -U postgres
env:
        - DJANGO_SETTINGS_MODULE=syah_site.settings.ci
        - SECRET_KEY="+&iy5xo9dad)e@1nmoxxn%ntdmo)krer#e5no50@74q62kwcrv"
script:
        - python manage.py test
