# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('pub_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(default='')),
            ],
        ),
    ]
